LEVELS = [
    # ── 1-10: Başlangıç ──────────
    {
        "title": 'Merhaba Roboto!',
        "hint": "Komutları sırayla seç, ardından ÇALIŞTIR'a bas. Roboto senin kodunu izleyecek!",
        "concept": 'Sıralama',
        "grid": [
            '########',
            '#S.....#',
            '#......#',
            '#.....G#',
            '########',
        ],
        "max_commands": 500, "stars3": 5, "stars2": 8,
    },
    {
        "title": 'Düz Yol',
        "hint": 'Hedefe ulaşmak için kaç adım gerekiyor? Doğru yönü seç ve ilerle.',
        "concept": 'Sıralama',
        "grid": [
            '##########',
            '#S.......#',
            '#........#',
            '#.......G#',
            '##########',
        ],
        "max_commands": 500, "stars3": 5, "stars2": 9,
    },
    {
        "title": 'İlk Köşe',
        "hint": 'Köşeyi dönmek için önce yönünü değiştir, sonra ilerle. Adımlarını planla!',
        "concept": 'Sıralama',
        "grid": [
            '#######',
            '#S....#',
            '#.###.#',
            '#...G.#',
            '#######',
        ],
        "max_commands": 500, "stars3": 5, "stars2": 8,
    },
    {
        "title": 'Zigzag',
        "hint": 'Duvarlar yolu kesiyor. Dikkatli planla ve etrafından dolan.',
        "concept": 'Sıralama',
        "grid": [
            '#########',
            '#S..#...#',
            '#...#...#',
            '#...#...#',
            '#.......#',
            '#.......#',
            '#...#..G#',
            '#########',
        ],
        "max_commands": 500, "stars3": 8, "stars2": 12,
    },
    {
        "title": 'Döngü Zamanı',
        "hint": 'Aynı komutu tekrar tekrar eklemek yerine TEKRAR x2 veya x3 kullan — çok daha hızlı!',
        "concept": 'Döngü',
        "grid": [
            '############',
            '#S..........#',
            '#...........#',
            '#..........G#',
            '############',
        ],
        "max_commands": 500, "stars3": 3, "stars2": 6,
    },
    {
        "title": 'Kare Yol',
        "hint": 'İç halkaya girmek için dış yoldan dol, açığı bul.',
        "concept": 'Döngü',
        "grid": [
            '#########',
            '#S......#',
            '#.#####.#',
            '#.#...#.#',
            '#.#.G.#.#',
            '#.#...#.#',
            '#.#.###.#',
            '#.......#',
            '#########',
        ],
        "max_commands": 500, "stars3": 6, "stars2": 9,
    },
    {
        "title": 'Engel Var!',
        "hint": 'Önünde bir duvar var. Sağdan mı yoksa soldan mı geçmek daha kısa?',
        "concept": 'Koşul',
        "grid": [
            '#########',
            '#S......#',
            '#...#...#',
            '#...#...#',
            '#...G...#',
            '#########',
        ],
        "max_commands": 500, "stars3": 6, "stars2": 10,
    },
    {
        "title": 'İki Engel',
        "hint": 'İki duvar sütunu yolu kesiyor. Aralarındaki boşluğu bul ve geç.',
        "concept": 'Koşul',
        "grid": [
            '##########',
            '#S.......#',
            '#..#..#..#',
            '#..#..#..#',
            '#........#',
            '#........#',
            '#.......G#',
            '##########',
        ],
        "max_commands": 500, "stars3": 7, "stars2": 12,
    },
    {
        "title": 'Labirent',
        "hint": 'Yol çok kıvrımlı — her adımı önceden planla. Az komutla çözmek 3 yıldız getirir!',
        "concept": 'Hepsi',
        "grid": [
            '###########',
            '#S.#.......#',
            '#..#.#####.#',
            '#..#.#...#.#',
            '#....#.#.#.#',
            '#####..#...#',
            '#......#.#.#',
            '#.######.#.#',
            '#........#G#',
            '###########',
        ],
        "max_commands": 500, "stars3": 12, "stars2": 17,
    },
    {
        "title": 'Büyük Final I',
        "hint": "Son bölüm! Tüm komutları ve TEKRAR'ı kullanman gerekebilir. İyi şanslar!",
        "concept": 'Hepsi',
        "grid": [
            '#############',
            '#S...........#',
            '#.###.#####.#',
            '#.#.....#...#',
            '#.#.###.#.###',
            '#...#.#...#.#',
            '#####.#.###.#',
            '#.....#.....#',
            '#.#########.#',
            '#..........G#',
            '#############',
        ],
        "max_commands": 500, "stars3": 14, "stars2": 20,
    },
    # ── 11-20: Orta ──────────
    {
        "title": 'Uzun Koridor',
        "hint": 'Dümdüz ama çok uzun — TEKRAR x3 kaç adım tasarruf sağlar?',
        "concept": 'Döngü',
        "grid": [
            '################',
            '#S............G#',
            '################',
        ],
        "max_commands": 500, "stars3": 3, "stars2": 6,
    },
    {
        "title": 'Geniş Alan',
        "hint": 'Geniş bir alan — hedefe en kısa yoldan ulaşmaya çalış.',
        "concept": 'Sıralama',
        "grid": [
            '#########',
            '#S......#',
            '#.......#',
            '#.......#',
            '#......G#',
            '#########',
        ],
        "max_commands": 500, "stars3": 10, "stars2": 15,
    },
    {
        "title": 'Duvar Engeli',
        "hint": 'Ortada bir duvar var — sağından veya solundan dolaşabilirsin.',
        "concept": 'Koşul',
        "grid": [
            '###########',
            '#S........#',
            '#....#....#',
            '#....#....#',
            '#....#...G#',
            '###########',
        ],
        "max_commands": 500, "stars3": 8, "stars2": 13,
    },
    {
        "title": 'Tek Köprü',
        "hint": 'Bu duvarda tek bir geçit var — onu bulup geç!',
        "concept": 'Koşul',
        "grid": [
            '###########',
            '#S........#',
            '#####.#####',
            '#.........#',
            '#........G#',
            '###########',
        ],
        "max_commands": 500, "stars3": 9, "stars2": 14,
    },
    {
        "title": 'Kıvrık Yol',
        "hint": 'Sağ taraf kapalı — önce aşağı in, sonra sağa git.',
        "concept": 'Sıralama',
        "grid": [
            '##########',
            '#S......##',
            '#.######.#',
            '#........#',
            '#.......G#',
            '##########',
        ],
        "max_commands": 500, "stars3": 9, "stars2": 14,
    },
    {
        "title": 'İki Köprü',
        "hint": 'İki duvar, iki geçit — her geçişi doğru planla!',
        "concept": 'Koşul',
        "grid": [
            '###########',
            '#S........#',
            '####.######',
            '#.........#',
            '######.####',
            '#.........#',
            '#........G#',
            '###########',
        ],
        "max_commands": 500, "stars3": 11, "stars2": 17,
    },
    {
        "title": 'S Yolu',
        "hint": 'Yol S harfi gibi kıvrılıyor — iki kez yön değiştirmen gerekecek.',
        "concept": 'Sıralama',
        "grid": [
            '##########',
            '#S.......#',
            '#.########',
            '#........#',
            '########.#',
            '#.......G#',
            '##########',
        ],
        "max_commands": 500, "stars3": 11, "stars2": 17,
    },
    {
        "title": 'U Yolu',
        "hint": 'Aşağı in, karşıya geç, yukarı çık — U şeklinde bir yol.',
        "concept": 'Sıralama',
        "grid": [
            '##########',
            '#S......##',
            '#.######.#',
            '#.......G#',
            '##########',
        ],
        "max_commands": 500, "stars3": 9, "stars2": 14,
    },
    {
        "title": 'Üç Köprü',
        "hint": 'Üç ayrı duvar engeli var — her geçişi doğru konumdan aş!',
        "concept": 'Koşul',
        "grid": [
            '###########',
            '#S........#',
            '#####.#####',
            '#.........#',
            '###.#######',
            '#.........#',
            '#######.###',
            '#.........#',
            '#........G#',
            '###########',
        ],
        "max_commands": 500, "stars3": 13, "stars2": 20,
    },
    {
        "title": 'Labirent 2',
        "hint": 'Zigzag koridorlar seni bekliyor. Sol kenara yapış ve ilerle!',
        "concept": 'Hepsi',
        "grid": [
            '############',
            '#S.........#',
            '#.##########',
            '#..........#',
            '##########.#',
            '#..........#',
            '#.##########',
            '#..........#',
            '##########.#',
            '#.........G#',
            '############',
        ],
        "max_commands": 500, "stars3": 20, "stars2": 30,
    },
    # ── 21-30: Zor ──────────
    {
        "title": 'Dört Köprü',
        "hint": 'Dört engel, dört geçit — çok dikkatli planla!',
        "concept": 'Koşul',
        "grid": [
            '###########',
            '#S........#',
            '##.########',
            '#.........#',
            '########.##',
            '#.........#',
            '##.########',
            '#.........#',
            '########.##',
            '#.........#',
            '#........G#',
            '###########',
        ],
        "max_commands": 500, "stars3": 15, "stars2": 24,
    },
    {
        "title": 'Uzun S Yolu',
        "hint": 'S yolunun daha uzun versiyonu — TEKRAR komutlarını akıllıca kullan.',
        "concept": 'Döngü',
        "grid": [
            '############',
            '#S.........#',
            '#.##########',
            '#..........#',
            '##########.#',
            '#..........#',
            '#.##########',
            '#..........G',
            '############',
        ],
        "max_commands": 500, "stars3": 16, "stars2": 25,
    },
    {
        "title": 'Çift U',
        "hint": 'İki U şeklini arka arkaya geçmen gerekiyor.',
        "concept": 'Sıralama',
        "grid": [
            '##############',
            '#S..........##',
            '#.##########.#',
            '#............#',
            '############.#',
            '#............#',
            '#.##########.#',
            '#...........G#',
            '##############',
        ],
        "max_commands": 500, "stars3": 18, "stars2": 28,
    },
    {
        "title": 'Oda Sistemi',
        "hint": 'Üç ayrı oda var — odalar arasındaki geçişleri bul.',
        "concept": 'Hepsi',
        "grid": [
            '##############',
            '#S....#......#',
            '#.....#......#',
            '#.....#......#',
            '####.#######.#',
            '#............#',
            '#.#######.####',
            '#.......#....#',
            '#.......#....#',
            '#.......#...G#',
            '##############',
        ],
        "max_commands": 500, "stars3": 18, "stars2": 28,
    },
    {
        "title": 'Büyük Labirent',
        "hint": 'Büyük ve karmaşık — duvarı takip et, çıkışı bulacaksın!',
        "concept": 'Hepsi',
        "grid": [
            '##############',
            '#S...........#',
            '#.####.#####.#',
            '#.#....#.....#',
            '#.#.##.#.####.',
            '#.#.#..#.....#',
            '#.#.#.##.###.#',
            '#...#....#.#.#',
            '#.####.#.#.#.#',
            '#......#...#G#',
            '##############',
        ],
        "max_commands": 500, "stars3": 22, "stars2": 34,
    },
    {
        "title": 'Uzun Zigzag',
        "hint": 'Uzun bir zigzag yolu — TEKRAR komutlarını tam burada kullan!',
        "concept": 'Döngü',
        "grid": [
            '################',
            '#S.............#',
            '#.##############',
            '#..............#',
            '##############.#',
            '#..............#',
            '#.##############',
            '#..............#',
            '##############.#',
            '#.............G#',
            '################',
        ],
        "max_commands": 500, "stars3": 24, "stars2": 38,
    },
    {
        "title": 'Çoklu Engel',
        "hint": 'Çok sayıda duvar — sistematik düşün, adım adım ilerle.',
        "concept": 'Hepsi',
        "grid": [
            '##############',
            '#S...........#',
            '#.##.####.##.#',
            '#..........#.#',
            '#.##.####..#.#',
            '#.#........#.#',
            '#.#.####.###.#',
            '#.#.........G#',
            '##############',
        ],
        "max_commands": 500, "stars3": 20, "stars2": 30,
    },
    {
        "title": 'Mega Labirent',
        "hint": 'En büyük labirent — sabırlı ol, çıkış mutlaka var!',
        "concept": 'Hepsi',
        "grid": [
            '################',
            '#S.............#',
            '#.##.########.##',
            '#..#..........##',
            '#.##.########.##',
            '#..............#',
            '##.########.####',
            '#..#..........##',
            '#.##.########.##',
            '#..............#',
            '#.########.###.#',
            '#..............G',
            '################',
        ],
        "max_commands": 500, "stars3": 30, "stars2": 46,
    },
    {
        "title": 'Efsane Yol',
        "hint": 'Çok uzun ve çok kıvrımlı — tüm komutlarını ve tekrarları kullan!',
        "concept": 'Hepsi',
        "grid": [
            '################',
            '#S.............#',
            '#.##############',
            '#..............#',
            '##############.#',
            '#..............#',
            '#.##############',
            '#..............#',
            '##############.#',
            '#..............#',
            '#.##############',
            '#..............G',
            '################',
        ],
        "max_commands": 500, "stars3": 30, "stars2": 48,
    },
    {
        "title": 'Büyük Final II',
        "hint": "Son ve en zor bölüm! Her şeyi kullan, Roboto'yu kurtar!",
        "concept": 'Hepsi',
        "grid": [
            '################',
            '#S.............#',
            '#.##.####.####.#',
            '#..#.#....#....#',
            '#.##.#.##.#.###.',
            '#....#..#.#...##',
            '#.####.##.#.####',
            '#.#....#..#....#',
            '#.#.##.#.###.#.#',
            '#...#..#.....#G#',
            '################',
        ],
        "max_commands": 500, "stars3": 28, "stars2": 44,
    },
    # ── 31-37: Uzman ──────────
    {
        "title": 'Yılan Yolu',
        "hint": 'Yol bir yılan gibi kıvrılıyor — sağa git, aşağı in, sola dön, tekrar et!',
        "concept": 'Döngü',
        "grid": [
            '###########',
            '#S........#',
            '#########.#',
            '#.........#',
            '#.#########',
            '#.........#',
            '#########.#',
            '#........G#',
            '###########',
        ],
        "max_commands": 500, "stars3": 16, "stars2": 24,
    },
    {
        "title": 'Ters Yılan',
        "hint": 'Bu kez yılan ters yönden başlıyor. Soldan sağa örgü gibi ilerle.',
        "concept": 'Döngü',
        "grid": [
            '###########',
            '#........S#',
            '#.#########',
            '#.........#',
            '#########.#',
            '#.........#',
            '#.#########',
            '#G........#',
            '###########',
        ],
        "max_commands": 500, "stars3": 16, "stars2": 24,
    },
    {
        "title": 'Sütunlar Arası',
        "hint": 'Sütunların arasından zikzak çizerek geç.',
        "concept": 'Koşul',
        "grid": [
            '###########',
            '#S........#',
            '#.#.#.#.#.#',
            '#.........#',
            '#.#.#.#.#.#',
            '#.........#',
            '#.#.#.#.#.#',
            '#........G#',
            '###########',
        ],
        "max_commands": 500, "stars3": 10, "stars2": 16,
    },
    {
        "title": 'Köprüler',
        "hint": 'Her duvarda tek bir köprü var — onları sırayla bul.',
        "concept": 'Koşul',
        "grid": [
            '###########',
            '#S........#',
            '##.########',
            '#.........#',
            '########.##',
            '#.........#',
            '##.########',
            '#........G#',
            '###########',
        ],
        "max_commands": 500, "stars3": 14, "stars2": 22,
    },
    {
        "title": 'Büyük Yılan',
        "hint": 'Daha uzun bir yılan! TEKRAR komutu çok işine yarar.',
        "concept": 'Döngü',
        "grid": [
            '#############',
            '#S..........#',
            '###########.#',
            '#...........#',
            '#.###########',
            '#...........#',
            '###########.#',
            '#...........#',
            '#.###########',
            '#..........G#',
            '#############',
        ],
        "max_commands": 500, "stars3": 30, "stars2": 46,
    },
    {
        "title": 'Sütun Tarlası',
        "hint": 'Sütun tarlasında kaybolma, satır satır ilerle.',
        "concept": 'Koşul',
        "grid": [
            '#############',
            '#S..........#',
            '#.#.#.#.#.#.#',
            '#...........#',
            '#.#.#.#.#.#.#',
            '#...........#',
            '#.#.#.#.#.#.#',
            '#...........#',
            '#.#.#.#.#.#.#',
            '#..........G#',
            '#############',
        ],
        "max_commands": 500, "stars3": 12, "stars2": 20,
    },
    {
        "title": 'Çok Köprü',
        "hint": 'Köprüler farklı yerlerde — her seferinde doğru deliğe yönel.',
        "concept": 'Koşul',
        "grid": [
            '#############',
            '#S..........#',
            '####.########',
            '#...........#',
            '########.####',
            '#...........#',
            '###.#########',
            '#...........#',
            '#########.###',
            '#..........G#',
            '#############',
        ],
        "max_commands": 500, "stars3": 16, "stars2": 26,
    },
    # ── 38-45: Cehennem (en zor labirentler) ──────────
    {
        "title": 'Çetin Labirent',
        "hint": 'Gerçek bir labirent! Çıkmaz sokaklara dikkat et, doğru yolu planla.',
        "concept": 'Hepsi',
        "grid": [
            '#############',
            '#S#.......#.#',
            '#.#.#.###.#.#',
            '#.#.#.#.....#',
            '#.#.#.#####.#',
            '#.#.#...#.#.#',
            '#.#####.#.#.#',
            '#...#...#...#',
            '###.#.###.###',
            '#.....#....G#',
            '#############',
        ],
        "max_commands": 500, "stars3": 42, "stars2": 67,
    },
    {
        "title": 'Dolambaçlı Yol',
        "hint": 'Yol kıvrım kıvrım ve aldatıcı — her dönüşü iyi düşün.',
        "concept": 'Hepsi',
        "grid": [
            '#############',
            '#S..#.......#',
            '###.###.###.#',
            '#...#...#...#',
            '#.###.###.###',
            '#...#.#...#.#',
            '###.#.###.#.#',
            '#.#.#...#...#',
            '#.#.###.###.#',
            '#.......#..G#',
            '#############',
        ],
        "max_commands": 500, "stars3": 46, "stars2": 73,
    },
    {
        "title": 'Kör Yollar',
        "hint": 'Pek çok çıkmaz sokak var. Yanlış yola sapma!',
        "concept": 'Hepsi',
        "grid": [
            '###############',
            '#S....#.......#',
            '#####.###.###.#',
            '#.....#...#.#.#',
            '#.#####.###.#.#',
            '#.#.....#.#...#',
            '#.#.###.#.#.###',
            '#.#.#...#...#.#',
            '#.###.###.###.#',
            '#.....#......G#',
            '###############',
        ],
        "max_commands": 500, "stars3": 52, "stars2": 83,
    },
    {
        "title": 'Usta Labirenti',
        "hint": 'Bunu sadece ustalar çözer. Sabırlı ol, adımlarını say.',
        "concept": 'Hepsi',
        "grid": [
            '###############',
            '#S..#.........#',
            '###.#####.###.#',
            '#.#.#.....#.#.#',
            '#.#.#.#####.#.#',
            '#...#.#...#...#',
            '#.###.#.#.#.###',
            '#...#.#.#...#.#',
            '###.#.#.#####.#',
            '#.....#......G#',
            '###############',
        ],
        "max_commands": 500, "stars3": 56, "stars2": 89,
    },
    {
        "title": 'Karmaşa',
        "hint": 'Karmakarışık koridorlar. Aklını kullan, kaybolma.',
        "concept": 'Hepsi',
        "grid": [
            '###############',
            '#S..#.......#.#',
            '###.###.###.#.#',
            '#.#.#...#...#.#',
            '#.#.#.###.###.#',
            '#...#...#.....#',
            '#.#####.#####.#',
            '#.#...#.....#.#',
            '#.#.#.#.###.#.#',
            '#...#.#.#...#.#',
            '#####.###.###.#',
            '#.........#..G#',
            '###############',
        ],
        "max_commands": 500, "stars3": 66, "stars2": 105,
    },
    {
        "title": 'Dev Dedalus',
        "hint": 'Devasa bir labirent — tek bir doğru yol var, onu bul.',
        "concept": 'Hepsi',
        "grid": [
            '###############',
            '#S#.....#.....#',
            '#.#.###.#####.#',
            '#...#.#.......#',
            '#####.#######.#',
            '#.#...#.....#.#',
            '#.#.#.#.#.###.#',
            '#...#.#.#.#...#',
            '#.###.#.#.#.###',
            '#.#.#...#...#.#',
            '#.#.#########.#',
            '#............G#',
            '###############',
        ],
        "max_commands": 500, "stars3": 66, "stars2": 105,
    },
    {
        "title": 'Son Sınav',
        "hint": 'Öğrendiğin her şey burada sınanıyor.',
        "concept": 'Hepsi',
        "grid": [
            '###############',
            '#S#.....#.....#',
            '#.###.#.###.#.#',
            '#.....#.#...#.#',
            '#######.#.###.#',
            '#.#...#...#...#',
            '#.#.#.#####.###',
            '#.#.#.....#.#.#',
            '#.#.###.###.#.#',
            '#...#.#.....#.#',
            '#.###.#######.#',
            '#............G#',
            '###############',
        ],
        "max_commands": 500, "stars3": 66, "stars2": 105,
    },
    {
        "title": 'Büyük Final III',
        "hint": "Son ve en zorlu labirent! Roboto'yu kurtar, efsane ol!",
        "concept": 'Hepsi',
        "grid": [
            '###############',
            '#S....#.....#.#',
            '#####.#.###.#.#',
            '#.....#.#.#...#',
            '#.#####.#.###.#',
            '#.#.....#.....#',
            '#.###.#.###.###',
            '#...#.#...#.#.#',
            '###.###.#.#.#.#',
            '#.#...#.#.#...#',
            '#.###.###.###.#',
            '#.........#..G#',
            '###############',
        ],
        "max_commands": 500, "stars3": 58, "stars2": 92,
    },
]
